language: bash

os:
  - linux

services: docker

before_script:
  - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
script:
  - docker-compose build

deploy:
  provider: script
  script: docker-compose push
  deploy.skip_cleanup: true
  on:
    all_branches: true

