language: bash

os:
  - linux

services: docker

before_script:
  - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
  - pip install --user shyaml

script:
  - docker-compose build cate-base
  - docker-compose build cate
  - docker-compose build cate-xcube
  - docker-compose build cate-jupyter
#  - docker-compose build cate-pangeo
  - docker-compose build cate-app-stage
  - docker-compose build cate-app-prod
  - docker-compose build cate-app-local

deploy:
  provider: script
  script: docker-compose push
  skip_cleanup: true
  on:
    tag: true

