version: '3'

services:
  cate-base:
    build:
      context: .
      dockerfile: cate-base.dockerfile
      args:
        - CATE_BASE_VERSION=${CATE_BASE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/ccitools/cate-base:${CATE_BASE_VERSION}
  cate:
    build:
      context: .
      dockerfile: cate.dockerfile
      args:
        - CATE_BASE_VERSION=${CATE_BASE_VERSION}
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/ccitools/cate:${CATE_VERSION}
    ports:
      - 4001:4000
  cate-jupyter:
    build:
      context: .
      dockerfile: cate-jupyter.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - JUPYTER_VERSION=${JUPYTER_VERSION}
    image: quay.io/ccitools/cate-jupyter:${CATE_VERSION}
  cate-app:
      build:
        context: .
        dockerfile: cate-webui.dockerfile
        args:
          - CATE_VERSION=${CATE_VERSION}
          - CATE_APP_VERSION=${CATE_APP_VERSION}
          - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
          - CATE_USER_NAME=${CATE_USER_NAME}
      image: quay.io/ccitools/cate-webui:${CATE_APP_VERSION}
      ports:
        - "82:80"

