version: '3'

services:
  cate-python-base:
    build:
      context: .
      dockerfile: cate-python-base.docker
      args:
        - CATE_USER_NAME=${CATE_USER_NAME}
        - CATE_PYTHON_BASE_VERSION=${CATE_PYTHON_BASE_VERSION}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/bcdev/cate-python-base:${CATE_PYTHON_BASE_VERSION}
  cate-python-deps:
    build:
      context: .
      dockerfile: cate-python-deps.docker
      args:
        - CATE_PYTHON_BASE_VERSION=${CATE_PYTHON_BASE_VERSION}
        - CATE_PYTHON_DEPS_VERSION=${CATE_PYTHON_DEPS_VERSION}
    image: quay.io/bcdev/cate-python-deps:${CATE_PYTHON_DEPS_VERSION}
  cate-web-api:
    build:
      context: .
      dockerfile: cate-web-api.docker
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_PYTHON_DEPS_VERSION=${CATE_PYTHON_DEPS_VERSION}
    image: quay.io/bcdev/cate-web-api:${CATE_VERSION}
