version: '3'

services:
  cate:
    build:
      context: .
      dockerfile: cate.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/bcdev/cate:${CATE_VERSION}
    ports:
      - 4000:4000
  cate-jupyter:
    build:
      context: .
      dockerfile: cate-jupyter.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - JUPYTER_VERSION=${JUPYTER_VERSION}
    image: quay.io/bcdev/cate-jupyter:${CATE_VERSION}
  cate-webui:
      build:
        context: .
        dockerfile: cate-webui.dockerfile
        args:
          - CATE_VERSION=${CATE_VERSION}
          - CATE_WEBUI_VERSION=${CATE_WEBUI_VERSION}
          - CATE_USER_NAME=${CATE_USER_NAME}
      image: quay.io/bcdev/cate-webui:${CATE_WEBUI_VERSION}
      ports:
        - "82:80"

