version: '3'

services:
  cate-jupyter:
    build:
      context: .
      dockerfile: cate-jupyter.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_INSTALL_MODE=${CATE_INSTALL_MODE}
        - JUPYTER_VERSION=${JUPYTER_VERSION}
        - XCUBE_VERSION=${XCUBE_VERSION}
        - XCUBE_CCI_VERSION=${XCUBE_CCI_VERSION}
    image: quay.io/ccitools/cate-jupyter:${CATE_VERSION}
