version: '3'

services:
  cate-python-base:
    build:
      context: .
      dockerfile: cate-python-base.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: quay.io/bcdev/cate-python-base:${CATE_VERSION}
  cate-python-deps:
    build:
      context: .
      dockerfile: cate-python-deps.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
    image: quay.io/bcdev/cate-python-deps:${CATE_VERSION}
  cate:
    build:
      context: .
      dockerfile: cate.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
    image: quay.io/bcdev/cate:${CATE_VERSION}
    ports:
      - 4001:4000
  cate-webapi-k8s:
    build:
      context: .
      dockerfile: cate-webapi-k8s.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_DOCKER_VERSION=${CATE_DOCKER_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
    image: quay.io/bcdev/cate-webapi-k8s:${CATE_VERSION}
    ports:
      - "8888:8888"
  cate-webui:
    build:
      context: .
      dockerfile: cate-webui.dockerfile
      args:
        - CATE_VERSION=${CATE_VERSION}
        - CATE_WEBUI_VERSION=${CATE_WEBUI_VERSION}
        - CATE_USER_NAME=${CATE_USER_NAME}
    image: quay.io/bcdev/cate-webui:${CATE_WEBUI_VERSION}
    ports:
      - "82:80"
